data:
  train_samples: 8
  num_minutes: 3

# format:
# <Transform Name>_<param name>: <value>
hparams:
  train:
    Crop_start: 0 # first 3 minutes in marsh data are unlabored breathing
    Crop_end: 180
    mask_probability: 0.08 # <NOT USED as of may 17th, 2024> probability of 
    convolve_length: 1 # smoothing factor for training
    jump_size: 10 # num samples that sliding window jumps forward for every train signal
    batchSize: 128 # data loader batch size
  test:
    Crop_start: 420 # 7th minute in marsh data is unlabored breathing
    Crop_end: 480

cwt_evaluation:
  low: 0.1
  high: 0.55
  resolution: 60

# transforms used in each global time series
# TODO explore highpassing the ecg to remove baseline wander
ecg_pipeline:
  - Crop
  - MinMaxScale # can be removed
  - MeanSubtraction
  - Detrend

ip_pipeline:
  - Crop
  - MinMaxScale # can be removed
  - MeanSubtraction
  - Detrend

# transforms for each individual time series used in training
dataloader_pipeline:
  - pass