data:
  train_samples: 8
  num_minutes: 3

# format:
# <Transform Name>_<param name>: <value>
hparams:
  jump_size: 10 # num samples that sliding window jumps forward for every train signal
  batch_size: 128 # data loader batch size
  seq_len: 512
  lr: 0.0003
  iters: 15

  # test:
  #   Crop_start: 420 # 7th minute in marsh data is unlabored breathing
  #   Crop_end: 480

cwt_evaluation:
  low: 0.1
  high: 0.55
  resolution: 60

# transforms used in each global time series
# TODO explore highpassing the ecg to remove baseline wander
global_ecg_pipeline:
  Crop:
    - start: 0 # first 3 minutes in marsh data are unlabored breathing
    - end: 180
  MinMaxScale: # can be removed
  MeanSubtraction:
  Detrend:

global_ip_pipeline:
  Crop:
    - start: 0 # first 3 minutes in marsh data are unlabored breathing
    - end: 180
  MinMaxScale: # can be removed
  MeanSubtraction:
  Detrend:

# transforms for each individual time series used in training
batch_ecg_pipeline:
  Detrend:

batch_ip_pipeline:

dataloader_pipeline: