desc: "A/B/C test comparing the use of LowPass/HighPass on training. ECG HP at 5. No LP on ECG"

data:
  train_samples: 14

learner_params:
  jump_size: 10 # num samples that sliding window jumps forward for every train signal
  batch_size: 128 # data loader batch size
  lr: 0.0003
  iters: 8

model_params:
  seq_len: 256
  n_heads: 16
  d_k: 32
  d_v: 32


  # test:
  #   Crop_start: 420 # 7th minute in marsh data is unlabored breathing
  #   Crop_end: 480

cwt_evaluation:
  low: 0.1
  high: 0.55
  resolution: 60

# transforms used in each global time series
# TODO explore highpassing the ecg to remove baseline wander
global_ecg_pipeline:
  Crop:
    - start: 0 # first 3 minutes in marsh data are unlabored breathing
    - end: 180
  MinMaxScale: # can be removed
    - _min: -0.0006556945871500413 # calculated with 14 train samples
    - _max: 0.002935897811694481
    - center: False
  # MeanSubtraction:
  Detrend:
  # LowPass:
  #   - cutoff: 35
  HighPass:
    - cutoff: 5

global_ip_pipeline:
  Crop:
    - start: 0 # first 3 minutes in marsh data are unlabored breathing
    - end: 180
  MinMaxScale: # can be removed
    - _min: -0.00016327855480638344
    - _max: 0.00032915616510091866
    - center: False
  # MeanSubtraction:
  Detrend:
  # HighPass:
  #   - cutoff: 0.05

# transforms for each individual time series used in training
batch_ecg_pipeline:
  # Detrend:

batch_ip_pipeline:

dataloader_pipeline: