desc: "pink noise test train only aug. 2000 filter order, 23 train samples, 5 iters A TEST"

data:
  train_samples: 23

learner_params:
  jump_size: 10 # num samples that sliding window jumps forward for every train signal
  batch_size: 128 # data loader batch size
  lr: 0.0003
  iters: 5

model_params:
  seq_len: 256
  d_model: 64
  n_layers: 4
  d_k: 8
  d_v: 8
  n_heads: 4

  # test:
  #   Crop_start: 420 # 7th minute in marsh data is unlabored breathing
  #   Crop_end: 480

cwt_evaluation:
  low: 0.10
  high: 0.55
  resolution: 60

# transforms used in each global time series
# TODO explore highpassing the ecg to remove baseline wander
global_ecg_pipeline:
  # Quantize:
  #   - precision: 16
  Crop:
    # - start: 10
    # - end: 180
    - start: [10, 310, 490, 730]
    - end: [170, 410, 600, 890]
  FIRFilter:
    - cutoff: 40
    - order: 2000
    - pass_zero_type: "lowpass"
  SSA:
    - window_size: 150
    - subtract_components: True
    - n_components: 1
  AddNoise:
    - noise_color: "pink"
    - scale: 0.00005
    - skip_eval: True

global_ip_pipeline:
  Crop:
    # - start: 10
    # - end: 180
    - start: [10, 310, 490, 730]
    - end: [170, 410, 600, 890]
  FIRFilter:
    - cutoff: 2
    - order: 2000
    - pass_zero_type: "lowpass"
  Detrend:

# transforms for each individual time series used in training
batch_ecg_pipeline:
  # Detrend:

batch_ip_pipeline:

dataloader_pipeline:

post_processing_pipeline:
  # ConvolveSmoothing: 
  #   - kernel_size: 1000
  FIRFilter:
    - cutoff: 2
    - order: 2000
    - pass_zero_type: "lowpass"
  Detrend:
  MinMaxScale:
    - center: True